format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[hostname]
format = "on [$hostname ]($style)"
style = 'green dimmed bold'
disabled = false

[directory]
format = "in [$path]($style) "
style = "blue"
truncation_length = 0

[character]
success_symbol = "[](purple)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[git_branch]
format = "[$symbol $branch]($style)"
symbol = ""
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
disabled = true

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[username]
format = '[$user]($style) '
style_root = 'red bold'
style_user = 'yellow bold'
show_always = false
disabled = false
